---
blank_issues_enabled: false
contact_links:
  - name: StarkNet Peer Review Community Support
    url: https://github.com/StarkNightsWatch/starknet-peer-review/discussions
    about: Please ask and answer questions here.
